import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google'; // 1. Change this
import './globals.css';

// 2. Replace the geistSans and geistMono blocks with this:
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
  weight: ['400', '500', '600', '700', '800'], // 800 is what your button needs
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 3. Update the body class to use the new variable */}
      <body className={`${plusJakartaSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}