import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';

import { AuthProvider } from '../context/AuthContext';
import { Footer } from '../components/footer/footer';
import { Header } from '../components/header/header';

// 1. IMPORT YOUR CART PROVIDER
import { CartProvider } from '../context/CartContext'; // Adjust path if your context folder is structured differently

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`} suppressHydrationWarning>
        {/* Providers must wrap components that use their context (Header/Footer) */}
        <CartProvider>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
          </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}